version: '3.7'
services:

  # MySQL
  db:
    container_name: ${APP_NAME}_db
    build:
      context: docker/services/mysql
    image: ${APP_NAME}/mysql
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
    command:
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/common/.profile:/root/.profile:ro
